source "http://rubygems.org"

# gem 'rails', '3.1.0.beta', :git => 'git://github.com/rails/rails.git'
# gem 'rails'
# gem 'configatron'
# gem 'hpricot'
# gem 'rmagick'
# gem 'htmlentities'
# gem 'haml'
# gem 'calendar_date_select'
# gem 'ri_cal'
# gem 'authlogic'
# gem 'searchlogic'
# gem 'rakismet'
# gem 'aws-s3'