configatron.default_mce_options = {
  :selector => 'textarea.rich_text_editor',
  :theme => 'modern',
  :browsers => %w{msie gecko safari},
  :theme_modern_layout_manager => "SimpleLayout",
  :theme_modern_statusbar_location => "bottom",
  :theme_modern_toolbar_location => "top",
  :theme_modern_toolbar_align => "left",
  :theme_modern_resizing => true,
  :relative_urls => false,
  :convert_urls => false,
  :cleanup => true,
  :cleanup_on_startup => true,
  :convert_fonts_to_spans => true,
  :theme_modern_resize_horizontal => false,
  :theme_modern_buttons1 => %w{bold italic underline separator justifyleft justifycenter justifyright indent outdent separator bullist numlist separator link unlink image media separator undo redo code},
  :theme_modern_buttons2 => [],
  :theme_modern_buttons3 => [],
  :plugins => %w{media link image preview autosave emoticons paste autoresize},
  :editor_deselector => "mceNoEditor",
  :extended_valid_elements => "img[class|src|flashvars|border=0|alt|title|hspace|vspace|width|height|align|onmouseover|onmouseout|name|obj|param|embed|scale|wmode|salign|style],embed[src|quality|scale|salign|wmode|bgcolor|width|height|name|align|type|pluginspage|flashvars],object[align<bottom?left?middle?right?top|archive|border|class|classid|codebase|codetype|data|declare|dir<ltr?rtl|height|hspace|id|lang|name|style|tabindex|title|type|usemap|vspace|width]",
  :media_strict => false
  }

configatron.simple_mce_options = {
    :selector => 'textarea.rich_text_editor',
  :theme => 'modern',
  :browsers => %w{msie gecko safari},
  :cleanup_on_startup => true,
  :convert_fonts_to_spans => true,
  :theme_modern_resizing => true,
  :theme_modern_toolbar_location => "top",
  :theme_modern_statusbar_location => "bottom",
  :editor_deselector => "mceNoEditor",
  :theme_modern_resize_horizontal => false,
  :theme_modern_buttons1 => %w{bold italic underline separator bullist numlist separator link unlink image},
  :theme_modern_buttons2 => [],
  :theme_modern_buttons3 => [],
  :plugins => %w{autosave link image emoticons },
  }
