require 'community_engine/engine'

require 'community_engine/authenticated_system'
require 'community_engine/localized_application'  
require 'community_engine/community_engine_sha1_crypto_method'    
require 'community_engine/i18n_extensions'  
require 'community_engine/viewable'    
require 'community_engine/url_upload'  

require 'configatron'
require 'configatron'
require 'hpricot'
require 'htmlentities'
require 'haml'
require 'ri_cal'
require 'rakismet'
# require 'aws/s3'
require 'will_paginate'
require 'dynamic_form'
require 'friendly_id'
require 'paperclip'
require 'acts_as_commentable'
require 'recaptcha/rails'
require 'simplecov'
require 'omniauth'
require 'authlogic'
#require 'acts_as_authentic'