source 'http://rubygems.org'

gem 'rails', '3.1.0.beta', :path => '../../../rails'
gem 'rack', :git => 'git://github.com/rack/rack.git'
gem 'arel',  :git => 'git://github.com/rails/arel.git'

gem 'community_engine', :path => '../../../community_engine'
gem "meta_search", :path => '../../../meta_search'
gem 'authlogic', :path => '../../../authlogic'

gem 'configatron'
gem 'hpricot'
gem 'htmlentities'
gem 'haml'
gem 'calendar_date_select', :git => 'http://github.com/paneq/calendar_date_select.git', :branch => 'rails3test'
gem 'ri_cal'
gem 'rakismet'
gem 'aws-s3', :require => 'aws/s3'
gem "will_paginate", "~> 3.0.pre2"
gem "dynamic_form"
gem "friendly_id", "~> 3.2.1"
gem "paperclip", "~> 2.3"
gem 'acts_as_commentable', "~> 3.0.0"
gem "recaptcha", :require => "recaptcha/rails"

gem 'sqlite3-ruby', :require => 'sqlite3'

